remote_theme: PfeifferChPT/pc-cdn-template
name: "IMPRINT PC-CDN"
title: "PC-CDN"
subtitle: "Imprint"
description: "" #metadescription
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title:output_ext/index.html
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: dlt
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: none
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
since: 2017
deactivaterelatedposts: true
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
